import fs from "node:fs";
import path from "node:path";

/**
 * Public OpenAPI document.
 *
 * Serves the committed Phase-A stub artifact at
 * `docs/openapi.stub.json` (regenerated by `pnpm openapi`). Reading
 * the file at module load — not per request — keeps the route
 * cheap and matches the rest of the runtime's "generated JSON,
 * loaded once" pattern. The stub is checked into git so consumers
 * see contract changes in PR diffs; this route just makes the same
 * artifact reachable from a chronicle-agnostic URL alongside the
 * rest of the API.
 *
 * Chronicle-agnostic on purpose: the document describes the full
 * `/api/{chronicle}` surface as a parameterised path, not a
 * per-chronicle spec. The `servers[].url` template inside the
 * document carries the `{chronicle}` placeholder.
 *
 * No envelope. OpenAPI consumers expect the raw spec object as the
 * response body, not `{ data: { …spec… } }`.
 */

const STUB_PATH = path.join(process.cwd(), "docs", "openapi.stub.json");

// Read once at module init. If the artifact is missing the route
// will throw at first request, surfacing the misconfiguration loudly
// rather than serving an empty / placeholder document.
const document: unknown = JSON.parse(fs.readFileSync(STUB_PATH, "utf-8"));

const headers: HeadersInit = {
  "Content-Type": "application/json",
  "Cache-Control": "public, max-age=86400",
};

export async function GET(): Promise<Response> {
  return new Response(JSON.stringify(document), { status: 200, headers });
}
