import { SUCCESS_CACHE_CONTROL } from "@/lib/api/responses";
import openApiStub from "../../../../docs/openapi.stub.json";

/**
 * Public OpenAPI document.
 *
 * Serves the committed Phase-A stub artifact at
 * `docs/openapi.stub.json` (regenerated by `pnpm openapi`). The stub
 * is imported statically so Next.js's NFT trace bundles the file
 * deterministically — no `process.cwd()` lookup, no per-request
 * filesystem read. The stub is checked into git so consumers see
 * contract changes in PR diffs; this route just makes the same
 * artifact reachable from a chronicle-agnostic URL alongside the
 * rest of the API.
 *
 * Chronicle-agnostic on purpose: the document describes the full
 * `/api/{chronicle}` surface as a parameterised path, not a
 * per-chronicle spec. The `servers[].url` template inside the
 * document carries the `{chronicle}` placeholder.
 *
 * No envelope. OpenAPI consumers expect the raw spec object as the
 * response body, not `{ data: { …spec… } }`.
 */

const headers: HeadersInit = {
  "Content-Type": "application/json",
  "Cache-Control": SUCCESS_CACHE_CONTROL,
};

const body = JSON.stringify(openApiStub);

export async function GET(): Promise<Response> {
  return new Response(body, { status: 200, headers });
}
