import { expect, test } from "vitest";
import { GET } from "@/app/api/openapi.json/route";

/**
 * Smoke test for `GET /api/openapi.json` — confirms the route serves
 * the committed stub document with the right content-type and the
 * Phase-A schema set the rest of the suite expects.
 *
 * The full document body is *not* snapshotted here — `docs/openapi.stub.json`
 * is the canonical artifact, regenerated by `pnpm openapi`, and is
 * already part of the repo's diff surface. Locking it twice would
 * just duplicate maintenance.
 */

const EXPECTED_SCHEMA_KEYS = [
  "ClassRef",
  "EnrichedSpawn",
  "HennaSummary",
  "LocationRef",
  "NpcRef",
  "QuestClientJournalEntry",
  "QuestRef",
  "RegionRef",
];

test("GET /api/openapi.json — status, content-type, expected schemas", async () => {
  const response = await GET();
  expect(response.status).toBe(200);
  expect(response.headers.get("content-type")).toMatch(/application\/json/);

  const body = (await response.json()) as {
    openapi: string;
    info: { title: string };
    components?: { schemas?: Record<string, unknown> };
  };

  expect(body.openapi).toMatch(/^3\.0/);
  expect(body.info.title).toBe("Lineage 2 API");

  const keys = Object.keys(body.components?.schemas ?? {}).sort();
  expect(keys).toEqual(EXPECTED_SCHEMA_KEYS);
});
