import { expect, test } from "vitest";
import { GET } from "@/app/api/openapi.json/route";

/**
 * Smoke tests for `GET /api/openapi.json` — confirms the route serves
 * the committed document with the right content-type, the expected
 * component-schema set, and endpoint-level path coverage for every
 * public route under `src/app/api/[chronicle]/`.
 *
 * The full document body is *not* snapshotted here — `docs/openapi.json`
 * is the canonical artifact, regenerated by `pnpm openapi`, and is
 * already part of the repo's diff surface (CI's OpenAPI drift gate).
 * Locking it twice would just duplicate maintenance.
 */

const EXPECTED_SCHEMA_KEYS = [
  "ApiError",
  "ArmorSet",
  "ClassDetail",
  "ClassRef",
  "ClassSummary",
  "Drop",
  "EnrichedSpawn",
  "ExchangeOption",
  "HennaDetail",
  "HennaSummary",
  "ItemDetail",
  "ItemQuantity",
  "ItemSourceEntry",
  "ItemSourceNpc",
  "ItemSummary",
  "ListMeta",
  "LocationRef",
  "NameCount",
  "NpcDetail",
  "NpcDrops",
  "NpcRef",
  "NpcSummary",
  "NpcTypeCount",
  "QuestClientJournalEntry",
  "QuestRef",
  "QuestDetail",
  "QuestSummary",
  "RawNpc",
  "RawSpawn",
  "RegionRef",
  "ShopProduct",
  "ShopView",
].sort();

// Every route under `src/app/api/[chronicle]/` must be represented.
// Adding a route without a spec entry (or vice versa) fails here.
const EXPECTED_PATHS = [
  "/{chronicle}/armor-sets",
  "/{chronicle}/classes",
  "/{chronicle}/classes/{id}",
  "/{chronicle}/drops/npc/{id}",
  "/{chronicle}/hennas",
  "/{chronicle}/hennas/{id}",
  "/{chronicle}/items",
  "/{chronicle}/items/{id}",
  "/{chronicle}/items/{id}/dropped-by",
  "/{chronicle}/items/{id}/spoiled-by",
  "/{chronicle}/locations",
  "/{chronicle}/meta/item-grades",
  "/{chronicle}/meta/item-types",
  "/{chronicle}/meta/npc-types",
  "/{chronicle}/monsters",
  "/{chronicle}/monsters/{id}",
  "/{chronicle}/monsters/{id}/drops",
  "/{chronicle}/npcs",
  "/{chronicle}/npcs/{id}",
  "/{chronicle}/npcs/{id}/drops",
  "/{chronicle}/npcs/{id}/shop",
  "/{chronicle}/npcs/{id}/spawns",
  "/{chronicle}/quests",
  "/{chronicle}/quests/{id}",
  "/{chronicle}/raw/monsters",
  "/{chronicle}/raw/monsters/{id}",
  "/{chronicle}/raw/monsters/{id}/spawns",
  "/{chronicle}/raw/npcs",
  "/{chronicle}/raw/npcs/{id}",
  "/{chronicle}/regions",
].sort();

interface OpenApiOperation {
  responses?: Record<string, unknown>;
  parameters?: Array<{ name: string; in: string }>;
}

interface OpenApiDocument {
  openapi: string;
  info: { title: string };
  components?: { schemas?: Record<string, unknown> };
  paths?: Record<string, { get?: OpenApiOperation }>;
}

async function fetchDocument(): Promise<OpenApiDocument> {
  const response = await GET();
  expect(response.status).toBe(200);
  expect(response.headers.get("content-type")).toMatch(/application\/json/);
  return (await response.json()) as OpenApiDocument;
}

test("GET /api/openapi.json — version, title, expected schemas", async () => {
  const body = await fetchDocument();

  expect(body.openapi).toBe("3.0.3");
  expect(body.info.title).toBe("Lineage 2 API");

  const keys = Object.keys(body.components?.schemas ?? {}).sort();
  expect(keys).toEqual(EXPECTED_SCHEMA_KEYS);
});

test("GET /api/openapi.json — every public route has a path entry", async () => {
  const body = await fetchDocument();

  const paths = Object.keys(body.paths ?? {}).sort();
  expect(paths).toEqual(EXPECTED_PATHS);
});

test("GET /api/openapi.json — operations carry chronicle param and 200/400/404 responses", async () => {
  const body = await fetchDocument();

  for (const [pathKey, item] of Object.entries(body.paths ?? {})) {
    const op = item.get;
    expect(op, `${pathKey} must define a GET operation`).toBeDefined();

    const responses = op?.responses ?? {};
    for (const status of ["200", "400", "404"]) {
      expect(responses[status], `${pathKey} must document a ${status}`).toBeDefined();
    }

    const chronicle = (op?.parameters ?? []).find(
      (p) => p.name === "chronicle" && p.in === "path"
    );
    expect(chronicle, `${pathKey} must take {chronicle} as a path param`).toBeDefined();
  }
});
